### ISSUE TITLE
Gradebook alignment issue.

### ISSUE THREAD

**Issue by vaughany** [dmuneras/moodle-theme_archaius#21]
Hi there.  We're having an issue with this otherwise wonderful theme, which I've not seen reported anywhere else.  We're using Moodle 2.7.1+ (20140821) with version 20140813 of Archaius.  The problem is reproducible in Chrome 37 and Firefox 32 on Ubuntu 14.04, as well as Chrome (unknown version) on Windows 7.

This first image shows the problem: the grades part of the gradebook does not line up with the user's names part of the gradebook:
![1-problem](https://cloud.githubusercontent.com/assets/381767/4186029/2f521e22-375d-11e4-9848-a5e62b973b18.png)

This second image shows me finding out (via Chrome's DevTools) that there is some extra top and bottom padding being applied to that part of the gradebook:
![2-problem-css](https://cloud.githubusercontent.com/assets/381767/4186053/5f380da4-375d-11e4-9977-fb91a936c1a2.png)

This last image shows that removing the top and bottom padding solves the issue (but only for the current session):
![3-solution](https://cloud.githubusercontent.com/assets/381767/4186070/96fd1bd0-375d-11e4-85f8-6964a9283839.png)

So removing that top and bottom padding seems to solve the problem, but I cannot find that CSS style in any stylesheet in theme/archaius/ or theme/base/, only in the 'all' file which the web browser loads but which doesn't seem to exist anywhere (probably only in Moodle's cache somewhere).

**Comment by Suzanadams** [comment]
Hello Guys, 

Thank you for helping us out.If you guys are using BCU theme, I fixed it by adding the following CSS code on the theme settings to fix the grade book, because the top headers get messed up, in order to solve this try:

.path-grade-report-grader div.left_scroller td, .path-grade-report-grader div.right_scroller td, .path-grade-report-grader div.left_scroller th, .path-grade-report-grader div.right_scroller th {
    font-size: 10px;
    height: 6.5em;	
}

.container-fluid {
    max-width: 100%;
    padding-right: 0px;
    padding-left: 0px;
}

Regards, 

Suzan
